#ifndef ENUMS_H
#define ENUMS_H

enum TOOL {BRUSH, ERASER, RECTANGLE, CIRCLE, TRIANGLE, POLYGON, SHAPE_TOOL, DRAG, SELECTOR, MOVETOP, MOVEBOTTOM};
enum COLOR {RED, ORANGE, YELLOW, GREEN, BLUE, PURPLE};
enum ACTION {NONE, CLEAR, UNDO, REDO};

#endif